# development:
#   adapter: postgresql
#   encoding: unicode
#   database: PetJoy_development
#   pool: 5
#   host: localhost
# test:
#   adapter: postgresql
#   encoding: unicode
#   database: PetJoy_test
#   pool: 5
#   host: localhost
# production:
#   adapter: postgresql
#   encoding: unicode
#   database: PetJoy_production
#   pool: 5

development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000